# makefile

# Dimitrios Paraschas
# 1562
# Dimitrios Greasidis
# 1624
# Stefanos Papanastasiou
# 1608


.PHONY: default
default: reset_server


# reset the server
reset_server:
	rm "configuration.json"
	rm "clients.json"
	rm "server.log"
